### ISSUE TITLE
Roadmap to v2

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#12]
[Wrangler 2.0.0 - Project Board](https://github.com/orgs/cloudflare/projects/1/views/1)

This is the parent issue tracking feature implementations and deprecations for wrangler v2. We commit to be not just feature complete, but also with a solid backward compatibility plan AND a migration plan for the deprecations being made. Expect this list to grow and shrink on the journey to completion. 

### Features:

- [x]  https://github.com/cloudflare/wrangler2/issues/1
- [x] https://github.com/cloudflare/wrangler2/issues/2
- [x] https://github.com/cloudflare/wrangler2/issues/6
- [x] https://github.com/cloudflare/wrangler2/issues/7
- [x] https://github.com/cloudflare/wrangler2/issues/10
- [x] #274
- [x] https://github.com/cloudflare/wrangler2/issues/4
- [x] https://github.com/cloudflare/wrangler2/issues/197
- [ ] https://github.com/cloudflare/wrangler2/issues/5
- [ ] https://github.com/cloudflare/wrangler2/issues/188
- [ ] #291

### Deprecations

- [ ] https://github.com/cloudflare/wrangler2/issues/8
- [ ] https://github.com/cloudflare/wrangler2/issues/9
- [ ] https://github.com/cloudflare/wrangler2/issues/14

### Smaller tasks 

- [x] https://github.com/cloudflare/wrangler2/issues/193
- [x] https://github.com/cloudflare/wrangler2/issues/205
- [x] #302
- [ ] #298
- [ ] #299
- [ ] https://github.com/cloudflare/wrangler2/issues/207
- [ ] https://github.com/cloudflare/wrangler2/issues/170
- [ ] https://github.com/cloudflare/wrangler2/issues/55
- [ ] some form of https://github.com/cloudflare/wrangler2/issues/190
- [ ] https://github.com/cloudflare/wrangler2/issues/185
- [ ] #300
- [ ] #301
- [ ] https://github.com/cloudflare/wrangler2/issues/3

**Comment by JacobMGEvans** [comment]
`whoami` command   https://github.com/cloudflare/wrangler2/issues/274

**Comment by petebacondarwin** [comment]
Closing as these are all now captured in the [Wrangler 2.0 Milestone)(https://github.com/cloudflare/wrangler2/milestone/1)

**Comment by huw** [comment]
Is there a good way to follow a milestone? Or will there be a blog post when it hits stable?

**Comment by petebacondarwin** [comment]
@huw - this is a good point. As far as I can tell there is no way to be notified on changes to a milestone.
I believe you can subscribe to releases from a repository...   but, for sure, when we release 2.0.0 there will be a blog post.

**Comment by JacobMGEvans** [comment]
@petebacondarwin is there a way to make the project publically viewable?
