### ISSUE TITLE
v2.1

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#151]
v2 features compatibility with v1, and we're tracking those. But we do want to start thinking of (and implementing) features for v2.1. This issue tracks the big headline features for v2.1 (This list is subject to change)

- [ ] https://github.com/cloudflare/wrangler2/issues/27
- [ ] https://github.com/cloudflare/wrangler2/issues/101
- [ ] https://github.com/cloudflare/wrangler2/issues/74
- [ ] https://github.com/cloudflare/wrangler2/issues/66
- [ ] https://github.com/cloudflare/wrangler2/issues/53
- [ ] https://github.com/cloudflare/wrangler2/issues/36
- [ ] https://github.com/cloudflare/wrangler2/issues/25
- [ ] #368
- [ ] #365
- [ ] #367
- [ ] https://github.com/cloudflare/wrangler2/issues/278

**Comment by petebacondarwin** [comment]
Closing as this is now captured in the [Wrangler 2.1](https://github.com/cloudflare/wrangler2/milestone/2)
