### ISSUE TITLE
Outstanding issues from v1 that we should fix in v2

### ISSUE THREAD

**Issue by threepointone** [cloudflare/wrangler2#19]
This is a running list of outstanding issues from wrangler v1 that we hope to fix in v2. 
- [x] https://github.com/cloudflare/wrangler/issues/2125
- [x] https://github.com/cloudflare/wrangler/issues/2120
- [x] https://github.com/cloudflare/wrangler/issues/2101
- [x] https://github.com/cloudflare/wrangler/issues/2094
- [x] https://github.com/cloudflare/wrangler/issues/2079
- [x] https://github.com/cloudflare/wrangler/issues/2067
- [x] https://github.com/cloudflare/wrangler/issues/2063
- [x] https://github.com/cloudflare/wrangler/issues/1998
- [x] https://github.com/cloudflare/wrangler/issues/1936
- [x] https://github.com/cloudflare/wrangler/issues/1910
- [x] https://github.com/cloudflare/wrangler/issues/1885
- [x] https://github.com/cloudflare/wrangler/issues/1820
- [x] https://github.com/cloudflare/wrangler/issues/1738
- [x] https://github.com/cloudflare/wrangler/issues/1951
- [x] https://github.com/cloudflare/wrangler/issues/1795
- [x] https://github.com/cloudflare/wrangler/issues/1511
- [x] https://github.com/cloudflare/wrangler/issues/1520
- [x] https://github.com/cloudflare/wrangler/issues/2103
- [x] https://github.com/cloudflare/wrangler/issues/2044
- [x] https://github.com/cloudflare/wrangler/issues/1978
- [x] https://github.com/cloudflare/wrangler/issues/1952
- [x] https://github.com/cloudflare/wrangler/issues/1875
- [x] https://github.com/cloudflare/wrangler/issues/1866
- [x] https://github.com/cloudflare/wrangler/issues/1767
- [x] https://github.com/cloudflare/wrangler/issues/1739
- [x] https://github.com/cloudflare/wrangler/issues/1737
- [x] https://github.com/cloudflare/wrangler/issues/1671
- [x] cloudflare/wrangler2#574
- [x] https://github.com/cloudflare/wrangler/issues/1529
- [x] cloudflare/wrangler2#569
- [x] https://github.com/cloudflare/wrangler/issues/2025
- [ ] cloudflare/wrangler2#696
- [ ] cloudflare/wrangler2#570
- [ ] https://github.com/cloudflare/wrangler/issues/1958
- [ ] cloudflare/wrangler2#571
- [ ] cloudflare/wrangler-action#68
- [ ] cloudflare/wrangler2#573
- [ ] https://github.com/cloudflare/wrangler/issues/2077

(will add more later, this is intimidatingly large already haha)

**Comment by threepointone** [comment]
Closing this issue since 2.0 is out, and we're following individual issues. We should also do a triage in wrangler 1 and close issues there with guidance, but we'll do that separately.
